- name: "Install Launchpad template"
  shell: "oc create -f https://raw.githubusercontent.com/openshiftio/launchpad-templates/{{ f8l_version }}/openshift/launchpad-template.yaml -n {{ namespace }}"

- name: "Retrieve Openshift Host"
  shell: "oc cluster status | grep 'Web console URL' | awk '{print $4}'"
  register: openshift_host

- name: "Create launch pad mission application"
  shell: "oc new-app launchpad -n {{ namespace }} -p LAUNCHPAD_MISSIONCONTROL_GITHUB_USERNAME={{ GITHUB_USER }} -p LAUNCHPAD_MISSIONCONTROL_GITHUB_TOKEN={{ GITHUB_TOKEN }} -p LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL={{ openshift_host.stdout }}"
